### ISSUE TITLE
Licence du projet ?

### ISSUE THREAD

**Issue by haubourg** [CEREMA/AgiRisk#2]
Bonjour et bravo pour ce projet incroyable que je découvre par les journées QGIS. 

Le code source n'a pas de licence explicite coté Github , et je vois coté site web une référence à une licence que je ne connais ( https://agirisk.cerema.fr/mise-en-oeuvre ) "open source innovation". 

Avez vous prévu de préciser cela ? Merci !

**Comment by ManuMarsu** [comment]
Merci de l'intérêt porté à ce projet. 
Il est vrai que la licence précise n'est pas encore définie à ce stade du projet, d'où le terme flou (amené à être corrigé) de licence "open source innovation". 
Comme indiqué lors des journées QGis, le projet a jusqu'à présent été développé en majorité sur des fonds publics et le type de licence qui en découle est résolument un type "ouvert" (CC-BY, CC-BY-SA, Licence ouverte Etalab, ...). 
Ce point sera sera précisé dans les semaines / mois à venir. Je laisse l'issue ouverte jusqu'à arbitrage officiel Cerema.

**Comment by haubourg** [comment]
Merci de votre réponse, je comprends parfaitement le temps nécessaire à choisir une licence. 
Deux points d'attention tout de même : 
- ne pas choisir de licence, c'est explicitement ne pas autoriser l'utilisation du logiciel : https://choosealicense.com/no-permission/ . C'est également prendre le risque d'abandonner vos copyright. En effet vous faites porter le risque sur l'utilisateur d'être en infraction avec le copyright - qui n'est pas matérialisé dans un fichier dédié, et les termes de réutilisation du code et du logiciel. 
- Ne pas confondre les licences dédiées open data que vous citez avec les licences dédiée logiciel comme GPL, AGPL, MIT etc... L'asssistant de choix de licence ici est plutôt bien réalisé : https://licence-libre.incubateur.anct.gouv.fr/licence-libre/le-point-sur-les-licences-libres

Bref, en général, mieux vaut choisir une licence dès le départ à la publication pour éviter ces risques, quitte à la changer plus tard

**Comment by ManuMarsu** [comment]
Merci des différents éléments fournis, qui nous ont été d'une grande aide pour choisir la licence du projet AgiRisk (dans sa composante logicielle tout du moins) : CeCILL v2.1
